=== iorfix/fantaasta/src/main/resources/fasta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
   targetNamespace="http://dati.fasta.org/struct" xmlns:tns="http://dati.fasta.org/struct" >


<xs:element name="proposte">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="proposta" type="tns:Proposta"  maxOccurs="10"/>
		</xs:sequence>
	</xs:complexType>
</xs:element>

<xs:complexType name="Proposta">
	<xs:sequence>
		<xs:element name="portieri" type="tns:Propostaruolo" />
		<xs:element name="difensori" type="tns:Propostaruolo" minOccurs="0" />
		<xs:element name="centrocampisti" type="tns:Propostaruolo" minOccurs="0"/>
		<xs:element name="attaccanti" type="tns:Propostaruolo" minOccurs="0" />
	</xs:sequence>
	<xs:attribute name="squadra" type="xs:string" />
	<xs:attribute name="riversacrediti" type="xs:boolean" />
</xs:complexType>

<xs:complexType name="Propostaruolo">
	<xs:sequence>
		<xs:element name="giocatore" type="tns:PropostaGiocatore" maxOccurs="unbounded" />
	</xs:sequence>
	<xs:attribute name="crediti" type="xs:int" />
</xs:complexType>

<xs:complexType name="PropostaGiocatore">
	<xs:attribute name="nome" type="xs:string" use="required" />
	<xs:attribute name="quota" type="xs:int" use="required"/>
</xs:complexType>


<xs:complexType name="GiocatoreElaborazione">
	<xs:attribute name="nome" type="xs:string" use="required"/>
	<xs:attribute name="squadra" type="xs:string" use="required"/>
	<xs:attribute name="quotaorg" type="xs:int" use="required"/>
	<xs:attribute name="quotacap" type="xs:int" use="required" />
	<xs:attribute name="quotafinale" type="xs:int" use="required"/>
	<xs:attribute name="ordine" type="xs:int" use="required"/>
	<xs:attribute name="random" type="xs:int" use="required"/>
	<xs:attribute name="posizioneAssegnazione" type="xs:int" use="required"/>
</xs:complexType>

<xs:complexType name="SquadraRuoloElaborazione">
	<xs:sequence>
		<xs:element name="squadra" type="xs:string" />
		<xs:element name="papabile" type="tns:GiocatoreElaborazione" minOccurs="0" maxOccurs="unbounded" />
		<xs:element name="assegnato" type="tns:GiocatoreElaborazione" minOccurs="0" maxOccurs="unbounded" />
		<xs:element name="crediti" type="tns:CreditiRuolo" />
	</xs:sequence>

</xs:complexType>

<xs:complexType name="CreditiRuolo">
	<xs:attribute name="creditiIniziali" type="xs:int" use="required" />
	<xs:attribute name="creditiRiportati" type="xs:int" use="required" />
	<xs:attribute name="creditiResidui" type="xs:int" use="required" />
		
</xs:complexType>

<xs:complexType name="ElaborazioneRuolo" >
	<xs:sequence>
		<xs:element name="squadra" type="tns:SquadraRuoloElaborazione" maxOccurs="unbounded"/>
	</xs:sequence>
</xs:complexType>

<xs:complexType name="SetupRuolo" >
	<xs:sequence>
		<xs:element name="squadra" type="xs:string" />
		<xs:element name="proposta" type="tns:Propostaruolo" />
		<xs:element name="creditiRiportati" type="xs:int" />
	</xs:sequence>
</xs:complexType>

<xs:complexType name="CreditiResiduiRuolo" >
	<xs:attribute name="squadra" type="xs:string" use="required"/>
	<xs:attribute name="crediti" type="xs:int" use="required"/>
</xs:complexType>

</xs:schema>

=== iorfix/fantaasta/src/test/resources/fasta_totale.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:proposte xmlns:tns="http://dati.fasta.org/struct"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://dati.fasta.org/struct ../../main/resources/fasta.xsd ">

	<proposta riversacrediti="false" squadra="S1">
		<portieri crediti="20">
			<giocatore nome="ALISSON" quota="18" />
			<giocatore nome="BERISHA" quota="18" />
			<giocatore nome="HANDANOVIC" quota="18" />
			<giocatore nome="GOLLINI" quota="17" />
			<giocatore nome="PADELLI" quota="17" />
			<giocatore nome="SKORUPSKI" quota="17" />
			<giocatore nome="BUFFON" quota="15" />
			<giocatore nome="DONNARUMMA G" quota="15" />
			<giocatore nome="REINA" quota="15" />
			<giocatore nome="STRAKOSHA" quota="15" />
			<giocatore nome="BELEC" quota="12" />
			<giocatore nome="CONSIGLI" quota="12" />
			<giocatore nome="CORDAZ" quota="12" />
			<giocatore nome="CRAGNO" quota="12" />
			<giocatore nome="MIRANTE" quota="12" />
			<giocatore nome="PERIN" quota="12" />
			<giocatore nome="SIRIGU" quota="12" />
			<giocatore nome="SORRENTINO" quota="12" />
			<giocatore nome="SPORTIELLO" quota="12" />
			<giocatore nome="VIVIANO" quota="12" />
			<giocatore nome="CROSTA" quota="10" />
			<giocatore nome="DA COSTA" quota="10" />
			<giocatore nome="GOMIS A" quota="10" />
			<giocatore nome="MARCHETTI" quota="10" />
			<giocatore nome="MERET" quota="10" />
			<giocatore nome="NICOLAS" quota="10" />
			<giocatore nome="PUGGIONI" quota="10" />
			<giocatore nome="RAFAEL" quota="10" />
			<giocatore nome="SANTURRO" quota="10" />
			<giocatore nome="SCUFFET" quota="10" />
		</portieri>
		<difensori crediti="60">
			<giocatore nome="BONUCCI" quota="53" />
			<giocatore nome="KOLAROV" quota="53" />
			<giocatore nome="KOULIBALY" quota="53" />
			<giocatore nome="PEZZELLA GER" quota="53" />
			<giocatore nome="ANDREOLLI" quota="50" />
			<giocatore nome="BARRECA" quota="50" />
			<giocatore nome="HATEBOER" quota="50" />
			<giocatore nome="SKRINIAR" quota="50" />
			<giocatore nome="BASTA" quota="40" />
			<giocatore nome="CACCIATORE" quota="40" />
			<giocatore nome="CANNAVARO" quota="40" />
			<giocatore nome="DE SILVESTRI" quota="40" />
			<giocatore nome="IZZO" quota="40" />
			<giocatore nome="MAIETTA" quota="40" />
			<giocatore nome="PALOMINO" quota="40" />
			<giocatore nome="TOLOI" quota="40" />
			<giocatore nome="ACERBI" quota="30" />
			<giocatore nome="ALEX SANDRO" quota="30" />
			<giocatore nome="RODRIGUEZ R" quota="30" />
			<giocatore nome="CALDARA" quota="20" />
			<giocatore nome="CHIELLINI" quota="20" />
			<giocatore nome="CONTI" quota="20" />
			<giocatore nome="DE VRIJ" quota="20" />
			<giocatore nome="ASTORI" quota="10" />
			<giocatore nome="BENATIA" quota="10" />
			<giocatore nome="BRUNO PERES" quota="10" />
			<giocatore nome="GHOULAM" quota="10" />
			<giocatore nome="HOWEDES" quota="10" />
			<giocatore nome="MANOLAS" quota="10" />
			<giocatore nome="MIRANDA" quota="10" />
			<giocatore nome="MUSACCHIO" quota="10" />
			<giocatore nome="N'KOULOU" quota="10" />
			<giocatore nome="RUGANI" quota="10" />
			<giocatore nome="ALBIOL" quota="5" />
			<giocatore nome="CANCELO" quota="5" />
			<giocatore nome="DALBERT" quota="5" />
			<giocatore nome="FAZIO" quota="5" />
			<giocatore nome="LICHTSTEINER" quota="5" />
			<giocatore nome="MASIELLO A" quota="5" />
			<giocatore nome="NUYTINCK" quota="5" />
			<giocatore nome="ROMAGNOLI A" quota="5" />
			<giocatore nome="ROMULO" quota="5" />
			<giocatore nome="D'AMBROSIO" quota="2" />
			<giocatore nome="DANILO" quota="2" />
			<giocatore nome="GAMBERINI" quota="2" />
			<giocatore nome="GASPAR" quota="2" />
			<giocatore nome="KARSDORP" quota="2" />
			<giocatore nome="RADU" quota="2" />
			<giocatore nome="SAMIR" quota="2" />
			<giocatore nome="BARZAGLI" quota="1" />
			<giocatore nome="BIRASCHI" quota="1" />
			<giocatore nome="CABRERA" quota="1" />
			<giocatore nome="CACERES" quota="1" />
			<giocatore nome="FERRARI A" quota="1" />
			<giocatore nome="FERRARI G" quota="1" />
			<giocatore nome="HECTOR MORENO" quota="1" />
			<giocatore nome="HEURTAUX" quota="1" />
			<giocatore nome="HYSAJ" quota="1" />
			<giocatore nome="JUAN JESUS" quota="1" />
			<giocatore nome="LAZAAR" quota="1" />
			<giocatore nome="LIROLA" quota="1" />
			<giocatore nome="LUCIONI" quota="1" />
			<giocatore nome="LUKAKU" quota="1" />
			<giocatore nome="LYANCO" quota="1" />
			<giocatore nome="MAKSIMOVIC" quota="1" />
			<giocatore nome="MARTELLA" quota="1" />
			<giocatore nome="MASINA" quota="1" />
			<giocatore nome="MURRU" quota="1" />
			<giocatore nome="PELUSO" quota="1" />
			<giocatore nome="PISACANE" quota="1" />
			<giocatore nome="REGINI" quota="1" />
			<giocatore nome="ROSSETTINI" quota="1" />
			<giocatore nome="SAMPIRISI" quota="1" />
			<giocatore nome="SILVESTRE" quota="1" />
			<giocatore nome="SOUPRAYEN" quota="1" />
			<giocatore nome="VAN DER WIEL" quota="1" />
			<giocatore nome="VICARI" quota="1" />
			<giocatore nome="VITOR HUGO" quota="1" />
			<giocatore nome="WALLACE" quota="1" />
			<giocatore nome="WIDMER" quota="1" />
		</difensori>
		<centrocampisti crediti="80">
			<giocatore nome="CHIESA" quota="73" />
			<giocatore nome="FLORENZI" quota="73" />
			<giocatore nome="NAINGGOLAN" quota="73" />
			<giocatore nome="PJANIC" quota="73" />
			<giocatore nome="BENASSI" quota="70" />
			<giocatore nome="DE PAUL" quota="70" />
			<giocatore nome="DE ROON" quota="70" />
			<giocatore nome="DE ROSSI" quota="70" />
			<giocatore nome="ILICIC" quota="70" />
			<giocatore nome="JOAO PEDRO" quota="70" />
			<giocatore nome="LUIS ALBERTO" quota="70" />
			<giocatore nome="RAMIREZ" quota="70" />
			<giocatore nome="VECINO" quota="70" />
			<giocatore nome="ALLAN" quota="60" />
			<giocatore nome="BASELLI" quota="60" />
			<giocatore nome="BIGLIA" quota="60" />
			<giocatore nome="BIRSA" quota="60" />
			<giocatore nome="BORJA VALERO" quota="60" />
			<giocatore nome="CASTRO" quota="60" />
			<giocatore nome="CRISTANTE" quota="60" />
			<giocatore nome="JOAO MARIO" quota="60" />
			<giocatore nome="VIVIANI" quota="60" />
			<giocatore nome="BERNARDESCHI" quota="50" />
			<giocatore nome="BONAVENTURA" quota="50" />
			<giocatore nome="CANDREVA" quota="50" />
			<giocatore nome="DOUGLAS COSTA" quota="50" />
			<giocatore nome="FELIPE ANDERSON" quota="50" />
			<giocatore nome="HAMSIK" quota="50" />
			<giocatore nome="MATUIDI" quota="50" />
			<giocatore nome="MILINKOVIC-SAVIC" quota="50" />
			<giocatore nome="PERISIC" quota="50" />
			<giocatore nome="SUSO" quota="50" />
			<giocatore nome="VERDI" quota="50" />
			<giocatore nome="ZIELINSKI" quota="50" />
			<giocatore nome="CALHANOGLU" quota="40" />
			<giocatore nome="CUADRADO" quota="40" />
			<giocatore nome="JANKTO" quota="40" />
			<giocatore nome="KESSIE'" quota="40" />
			<giocatore nome="KHEDIRA" quota="40" />
			<giocatore nome="LULIC" quota="40" />
			<giocatore nome="PAROLO" quota="40" />
			<giocatore nome="PEROTTI" quota="40" />
			<giocatore nome="STROOTMAN" quota="40" />
			<giocatore nome="CICIRETTI" quota="30" />
			<giocatore nome="DI FRANCESCO F" quota="30" />
			<giocatore nome="EYSSERIC" quota="30" />
			<giocatore nome="FOFANA" quota="30" />
			<giocatore nome="GAGLIARDINI" quota="30" />
			<giocatore nome="IONITA" quota="30" />
			<giocatore nome="KURTIC" quota="30" />
			<giocatore nome="LUCAS LEIVA" quota="30" />
			<giocatore nome="SAPONARA" quota="30" />
			<giocatore nome="VERETOUT" quota="30" />
			<giocatore nome="BADELJ" quota="20" />
			<giocatore nome="CENTURION" quota="20" />
			<giocatore nome="D'ALESSANDRO" quota="20" />
			<giocatore nome="FREULER" quota="20" />
			<giocatore nome="GIL DIAS" quota="20" />
			<giocatore nome="LAZZARI M" quota="20" />
			<giocatore nome="MARCHISIO" quota="20" />
			<giocatore nome="PELLEGRINI" quota="20" />
			<giocatore nome="PRAET" quota="20" />
			<giocatore nome="TAIDER" quota="20" />
			<giocatore nome="UNDER" quota="20" />
			<giocatore nome="ALVAREZ R" quota="10" />
			<giocatore nome="BENASSI" quota="10" />
			<giocatore nome="BERENGUER" quota="10" />
			<giocatore nome="BERTOLACCI" quota="10" />
			<giocatore nome="BESSA" quota="10" />
			<giocatore nome="BROZOVIC" quota="10" />
			<giocatore nome="DIAWARA" quota="10" />
			<giocatore nome="DONSAH" quota="10" />
			<giocatore nome="HALLFREDSSON" quota="10" />
			<giocatore nome="KREJCI" quota="10" />
			<giocatore nome="LAXALT" quota="10" />
			<giocatore nome="LAZOVIC" quota="10" />
			<giocatore nome="MISSIROLI" quota="10" />
			<giocatore nome="SENSI" quota="10" />
			<giocatore nome="SPINAZZOLA" quota="10" />
			<giocatore nome="TORREIRA" quota="10" />
		</centrocampisti>


		<attaccanti crediti="100">
			<giocatore nome="BELOTTI" quota="95" />
			<giocatore nome="DYBALA" quota="95" />
			<giocatore nome="ICARDI" quota="95" />
			<giocatore nome="KALINIC" quota="95" />
			<giocatore nome="DZEKO" quota="80" />
			<giocatore nome="GOMEZ A" quota="80" />
			<giocatore nome="INSIGNE" quota="80" />
			<giocatore nome="MERTENS" quota="80" />
			<giocatore nome="BORRIELLO" quota="60" />
			<giocatore nome="CORNELIUS" quota="60" />
			<giocatore nome="IAGO FALQUE" quota="60" />
			<giocatore nome="IMMOBILE" quota="60" />
			<giocatore nome="LJAJIC" quota="60" />
			<giocatore nome="PALACIO" quota="60" />
			<giocatore nome="PALOSCHI" quota="60" />
			<giocatore nome="PAVOLETTI" quota="60" />
			<giocatore nome="QUAGLIARELLA" quota="60" />
			<giocatore nome="RAGUSA" quota="60" />
			<giocatore nome="SIMEONE" quota="60" />
			<giocatore nome="CALLEJON" quota="50" />
			<giocatore nome="HIGUAIN" quota="50" />
			<giocatore nome="FALCINELLI" quota="40" />
			<giocatore nome="MANDZUKIC" quota="40" />
			<giocatore nome="PAZZINI" quota="40" />
			<giocatore nome="SCHICK" quota="40" />
			<giocatore nome="THEREAU" quota="40" />
			<giocatore nome="ANDRE' SILVA" quota="30" />
			<giocatore nome="BERARDI" quota="30" />
			<giocatore nome="DEFREL" quota="30" />
